const initialFilms = [
  {
    link: 'https://i.ibb.co/C2QM1Fp/pic-COLOR-pic.png',
    duration: '1ч42м',
    id: 1,
    title: '33 слова о дизайне',
    saved: true,
  },
  {
    link: 'https://i.ibb.co/pZRYQwk/pic-COLOR-pic2.png',
    duration: '1ч42м',
    id: 2,
    title: 'Киноальманах «100 лет дизайна»',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/njrjW7c/pic-COLOR-pic3.png',
    duration: '1ч42м',
    id: 3,
    title: 'В погоне за Бенкси',
    saved: true,
  },
  {
    link: 'https://i.ibb.co/J7HySCm/pic-COLOR-pic4.png',
    duration: '1ч42м',
    id: 4,
    title: 'Баския: Взрыв реальности',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/4ZmVXhc/pic-COLOR-pic5.png',
    duration: '1ч42м',
    id: 5,
    title: 'Бег это свобода',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/MVHT7WH/pic-COLOR-pic6.png',
    duration: '1ч42м',
    id: 6,
    title: 'Книготорговцы',
    saved: true,
  },
  {
    link: 'https://i.ibb.co/Tv2gHSC/pic-COLOR-pic7.png',
    duration: '1ч42м',
    id: 7,
    title: 'Когда я думаю о Германии ночью',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/K0DfZJP/pic-COLOR-pic8.png',
    duration: '1ч42м',
    id: 8,
    title: 'Gimme Danger: История Игги и The Stooges',
    saved: false,
  }, {
    link: 'https://i.ibb.co/56S8NqN/pic-COLOR-pic9.png',
    duration: '1ч42м',
    id: 9,
    title: 'Дженис: Маленькая девочка грустит',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/vmXTs1s/pic-COLOR-pic10.png',
    duration: '1ч42м',
    id: 10,
    title: 'Соберись перед прыжком',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/ZBs5XnR/pic-COLOR-pic11.png',
    duration: '1ч42м',
    id: 11,
    title: 'Пи Джей Харви: A dog called money',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/XWyWnBb/pic-COLOR-pic12.png',
    duration: '1ч42м',
    id: 12,
    title: 'По волнам: Искусство звука в кино',
    saved: false,
  }, {
    link: 'https://i.ibb.co/fxTk17Y/pic-COLOR-pic13.png',
    duration: '1ч42м',
    id: 13,
    title: 'Рудбой',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/MpSfGNv/pic-COLOR-pic14.png',
    duration: '1ч42м',
    id: 14,
    title: 'Скейт — кухня',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/Np4gtFV/pic-COLOR-pic15.png',
    duration: '1ч42м',
    id: 15,
    title: 'Война искусств',
    saved: false,
  },
  {
    link: 'https://i.ibb.co/kBdVkjq/pic-COLOR-pic16.png',
    duration: '1ч42м',
    id: 16,
    title: 'Зона',
    saved: false,
  },
];

export default initialFilms;
